import type { AdminMobileScreen } from "@/types/admin";

// Mock data for the small-screen ("mobile") variant of the Admin Console.
export const MOBILE_ADMIN_SCREENS: AdminMobileScreen[] = [
  {
    id: "dash",
    navLabel: "개요",
    navDot: "#2B4BF2",
    title: "관리자",
    sub: "gxsoft.co.kr · 실시간",
    caption: "관리자 · 개요",
    chips: ["오늘", "7일", "30일"],
    rows: [
      { tone: "info", name: "일 처리량", meta: "24.9만", line3: "전일 대비 +6.2%" },
      { tone: "danger", name: "차단 · 격리", meta: "24,918", line3: "격리 312건 · 위험 높음 18" },
      { tone: "neutral", name: "발송 큐", meta: "1,204", line3: "재시도 18 · 실패 3" },
      { tone: "success", name: "평균 배달 지연", meta: "1.8초", line3: "SLA 5초 이내", tag: "정상", tagTone: "success" },
      { tone: "warning", name: "확인 필요 2건", line3: "MTA-STS 미적용 · 용량 임계 8건", tag: "보기", tagTone: "warning", on: true },
    ],
    footerText: "전체 리포트는 데스크톱에서 확인하세요",
  },
  {
    id: "users",
    navLabel: "계정",
    navDot: "#B9C6FA",
    title: "계정",
    sub: "1,284개 · 정지 3 · 비활성 26",
    caption: "관리자 · 계정",
    actionLabel: "⌕",
    chips: ["전체", "정지", "비활성"],
    rows: [
      { tone: "info", avatar: "한지", name: "한지우", line3: "전략기획팀 · 18.2 GB", tag: "정상", tagTone: "success" },
      { tone: "neutral", avatar: "박서", name: "박서준", line3: "인프라팀 · 32.4 GB", tag: "정상", tagTone: "success" },
      { tone: "warning", avatar: "윤재", name: "윤재호", line3: "영업팀 · 47.8 GB", tag: "용량", tagTone: "warning" },
      { tone: "danger", avatar: "임시", name: "temp-001", line3: "미지정 · 90일 미접속", tag: "정지", tagTone: "danger" },
      { tone: "neutral", avatar: "오세", name: "오세린", line3: "대표이사실 · 8.1 GB", tag: "정상", tagTone: "success" },
    ],
    footerText: "스와이프로 정지 · 길게 눌러 비밀번호 초기화",
    footerBtn: "정지",
  },
  {
    id: "security",
    navLabel: "보안",
    navDot: "#C0433B",
    title: "보안",
    sub: "최근 7일 · 조치 대기 3건",
    caption: "관리자 · 보안 로그",
    chips: ["전체", "높음"],
    rows: [
      { tone: "danger", name: "비정상 로그인 시도", line2: "오사카, 일본 · 12건 차단", line3: "8일 전 · 조치 완료" },
      { tone: "danger", name: "피싱 캠페인 탐지", line2: "유사 도메인 gxsott.co.kr", line3: "오늘 06:12 · 격리 28건", tag: "대기", tagTone: "danger", on: true },
      { tone: "warning", name: "DLP 차단", line2: "실행 파일 첨부 발송 시도", line3: "어제 · 3건" },
      { tone: "warning", name: "SPF 실패 급증", line2: "mail.gxsoft.co.kr", line3: "어제 · 평판 78점", tag: "대기", tagTone: "warning" },
      { tone: "neutral", name: "앱 비밀번호 사용", line2: "IMAP 클라이언트 2개", line3: "6일 전 · 검토 권장" },
    ],
    footerText: "규칙 변경은 데스크톱에서만 가능합니다",
  },
  {
    id: "quarantine",
    navLabel: "격리 검토",
    navDot: "#E3B5B0",
    title: "격리 검토",
    sub: "312건 · 위험 높음 18건",
    caption: "관리자 · 격리 검토",
    chips: ["높음", "스팸", "전체"],
    rows: [
      { tone: "danger", name: "security-alert@gxsott.co.kr", line2: "긴급: 비밀번호가 만료되었습니다", line3: "수신자 84명 · 유사 도메인", tag: "삭제", tagTone: "danger", on: true },
      { tone: "danger", name: "invoice@paymnet-secure.net", line2: "미결제 청구서", line3: "수신자 12명 · 실행 파일", tag: "삭제", tagTone: "danger" },
      { tone: "warning", name: "newsletter@marketing-hub.io", line2: "9월 신제품 소식", line3: "수신자 206명 · SPF 실패", tag: "보류", tagTone: "warning" },
      { tone: "neutral", name: "hr@partner-corp.kr", line2: "채용 협업 제안", line3: "수신자 2명 · 첫 수신", tag: "복원", tagTone: "neutral" },
      { tone: "neutral", name: "billing@cloudvendor.com", line2: "8월 사용량 명세서", line3: "수신자 4명 · 정상 가능성", tag: "복원", tagTone: "neutral" },
    ],
    footerText: "일괄 삭제는 감사 로그에 기록됩니다",
    footerBtn: "일괄 삭제",
  },
  {
    id: "status",
    navLabel: "서비스 상태",
    navDot: "#3FBF7F",
    title: "서비스 상태",
    sub: "모든 서비스 정상",
    caption: "관리자 · 상태 · 공지",
    actionLabel: "＋",
    rows: [
      { tone: "success", name: "메일 수신 · 발송", line3: "가동률 99.98% (30일)", tag: "정상", tagTone: "success" },
      { tone: "success", name: "웹 클라이언트", line3: "p95 응답 118ms", tag: "정상", tagTone: "success" },
      { tone: "success", name: "IMAP · SMTP", line3: "연결 2,412개", tag: "정상", tagTone: "success" },
      { tone: "warning", name: "메일함 이전", line3: "배치 4개 진행 · 대역폭 제한", tag: "지연", tagTone: "warning" },
      { tone: "info", name: "예정된 점검", line2: "9월 6일 02:00 – 04:00", line3: "배너 게시 중 · 수신은 계속", tag: "게시", tagTone: "info", on: true },
    ],
    footerText: "점검 배너는 전 사용자에게 표시됩니다",
  },
  {
    id: "groups",
    navLabel: "그룹",
    navDot: "#E3B5B0",
    title: "그룹",
    sub: "42개 · 메일링 12",
    caption: "관리자 · 그룹",
    actionLabel: "＋",
    chips: ["전체", "부서", "메일링"],
    rows: [
      { tone: "info", avatar: "전략", name: "전략기획팀", meta: "38명", line3: "strategy · 부서 그룹" },
      { tone: "neutral", avatar: "인프", name: "인프라팀", meta: "24명", line3: "infra · 부서 그룹" },
      { tone: "warning", avatar: "전사", name: "전사 공지", meta: "1,284명", line3: "all · 발신 제한", tag: "제한", tagTone: "warning", on: true },
      { tone: "neutral", avatar: "영업", name: "영업 1팀", meta: "31명", line3: "sales1 · 부서 그룹" },
      { tone: "neutral", avatar: "오로", name: "프로젝트 오로라", meta: "9명", line3: "aurora · 임시 · 12월 만료", tag: "임시", tagTone: "warning" },
    ],
    footerText: "멤버 편집은 길게 눌러 선택하세요",
  },
  {
    id: "policy",
    navLabel: "도메인 · 정책",
    navDot: "#E0AC4A",
    title: "도메인 · 정책",
    sub: "3개 도메인 · 조치 1건",
    caption: "관리자 · 도메인 · 정책",
    chips: ["도메인", "인증"],
    rows: [
      { tone: "info", name: "gxsoft.co.kr", line3: "주 도메인 · SPF · DKIM · DMARC", tag: "정상", tagTone: "success" },
      { tone: "neutral", name: "mail.gxsoft.co.kr", line3: "발송 전용 · 평판 78점", tag: "경고", tagTone: "warning", on: true },
      { tone: "neutral", name: "gxsoft.kr", line3: "별칭 · 수신 전달", tag: "정상", tagTone: "success" },
      { tone: "neutral", name: "DMARC 정책", line3: "p=quarantine · 리포트 주 1회" },
      { tone: "warning", name: "MTA-STS 미적용", line3: "권장 · 중간자 공격 차단", tag: "조치", tagTone: "warning" },
    ],
    footerText: "정책 변경은 데스크톱에서만 가능합니다",
  },
  {
    id: "audit",
    navLabel: "감사 로그",
    navDot: "#3B7A94",
    title: "감사 로그",
    sub: "최근 24시간 · 218건",
    caption: "관리자 · 감사 로그",
    actionLabel: "⌕",
    chips: ["전체", "권한", "삭제"],
    rows: [
      { tone: "info", name: "관리자 권한 부여", meta: "09:24", line2: "오세린 → 박서준", line3: "IP 10.2.14.8 · 웹 콘솔" },
      { tone: "neutral", name: "메일함 위임 해제", meta: "08:51", line2: "shared-hr · 한지우", line3: "IP 10.2.9.31" },
      { tone: "danger", name: "일괄 삭제 실행", meta: "07:12", line2: "격리 메일 84건", line3: "박서준 · 되돌릴 수 없음", tag: "중요", tagTone: "danger", on: true },
      { tone: "neutral", name: "정책 수정", meta: "어제", line2: "DLP 실행 파일 차단 ON", line3: "오세린" },
      { tone: "neutral", name: "API 키 발급", meta: "어제", line2: "billing-sync", line3: "인프라팀 · 만료 90일" },
    ],
    footerText: "로그는 7년 보관 · 내보내기는 데스크톱",
  },
  {
    id: "backup",
    navLabel: "백업",
    navDot: "#2E8B5B",
    title: "백업",
    sub: "일 1회 · 최근 성공 03:10",
    caption: "관리자 · 백업",
    chips: ["작업", "복원"],
    rows: [
      { tone: "success", name: "전체 백업", meta: "03:10", line3: "1.8 TB · 42분 소요", tag: "성공", tagTone: "success" },
      { tone: "success", name: "증분 백업", meta: "매시", line3: "최근 12회 연속 성공", tag: "성공", tagTone: "success" },
      { tone: "warning", name: "복원 테스트", meta: "23일 전", line3: "분기 1회 권장 · 기한 임박", tag: "권장", tagTone: "warning", on: true },
      { tone: "neutral", name: "보존 정책", line3: "메일 7년 · 감사 로그 7년" },
      { tone: "neutral", name: "스토리지 사용", meta: "62%", line3: "4.9 TB / 8 TB" },
    ],
    footerText: "복원은 데스크톱 콘솔에서 요청하세요",
  },
  {
    id: "billing",
    navLabel: "요금",
    navDot: "#D4D4CE",
    title: "요금",
    sub: "9월 청구 예정 ₩3,852,000",
    caption: "관리자 · 요금",
    chips: ["이번 달", "지난 달"],
    rows: [
      { tone: "info", name: "사용 좌석", meta: "1,284", line3: "계약 1,400석 · 여유 116석" },
      { tone: "neutral", name: "추가 스토리지", meta: "2 TB", line3: "₩320,000 · 월 정액" },
      { tone: "neutral", name: "아카이브 보관", meta: "6 TB", line3: "₩540,000 · 7년 보존" },
      { tone: "neutral", name: "8월 청구", meta: "₩3,796,400", line3: "결제 완료 · 8월 31일", tag: "완료", tagTone: "success" },
      { tone: "warning", name: "카드 만료 임박", line3: "법인카드 ****4821 · 11월 만료", tag: "조치", tagTone: "warning", on: true },
    ],
    footerText: "세금계산서는 등록 메일로 발송됩니다",
  },
  {
    id: "brand",
    navLabel: "브랜딩",
    navDot: "#8E7CC3",
    title: "브랜딩",
    sub: "로고 · 색상 · 서명",
    caption: "관리자 · 브랜딩",
    chips: ["적용", "초안"],
    rows: [
      { tone: "info", name: "로고", line3: "SVG · 라이트 · 다크 등록", tag: "적용", tagTone: "success" },
      { tone: "neutral", name: "강조 색상", line3: "로그인 · 버튼 · 링크에 반영", tag: "적용", tagTone: "success" },
      { tone: "neutral", name: "메일 서명 템플릿", line3: "부서별 3종 · 자동 삽입" },
      { tone: "neutral", name: "로그인 배경", line3: "이미지 미등록 · 기본 사용", tag: "초안", tagTone: "warning", on: true },
      { tone: "neutral", name: "시스템 메일 발신자명", line3: "GXSOFT 메일 · no-reply" },
    ],
    footerText: "변경은 승인 후 전사에 적용됩니다",
  },
  {
    id: "api",
    navLabel: "API",
    navDot: "#3B7A94",
    title: "API",
    sub: "키 4개 · 호출 1.2만/일",
    caption: "관리자 · API",
    actionLabel: "＋",
    chips: ["키", "웹훅"],
    rows: [
      { tone: "info", name: "hr-sync", line3: "읽기 · 계정 · 최근 호출 2분 전", tag: "활성", tagTone: "success" },
      { tone: "neutral", name: "billing-sync", line3: "읽기 · 사용량 · 만료 82일", tag: "활성", tagTone: "success" },
      { tone: "warning", name: "legacy-import", line3: "쓰기 · 만료 6일 · 회전 권장", tag: "만료", tagTone: "warning", on: true },
      { tone: "neutral", name: "웹훅 · 격리 알림", line3: "POST /hooks/quarantine · 100%" },
      { tone: "neutral", name: "레이트 리밋", meta: "600/분", line3: "초과 시 429 · 재시도 권장" },
    ],
    footerText: "키 값은 발급 시 한 번만 표시됩니다",
  },
  {
    id: "approval",
    navLabel: "승인 흐름",
    navDot: "#6B5CA8",
    title: "승인 흐름",
    sub: "대기 6건 · 평균 4.2시간",
    caption: "관리자 · 승인 흐름",
    chips: ["대기", "완료"],
    rows: [
      { tone: "warning", name: "대량 발송 승인", line2: "전사 공지 · 1,284명", line3: "요청 한지우 · 2시간 전", tag: "대기", tagTone: "warning", on: true },
      { tone: "warning", name: "외부 공유 예외", line2: "partner-corp.kr 첨부 허용", line3: "요청 영업1팀 · 5시간 전", tag: "대기", tagTone: "warning" },
      { tone: "neutral", name: "계정 삭제", line2: "temp-001 · 데이터 파기", line3: "요청 인프라팀 · 어제", tag: "대기", tagTone: "warning" },
      { tone: "neutral", name: "정책 예외 · DLP", line2: "실행 파일 1회 발송", line3: "승인 완료 · 오세린", tag: "완료", tagTone: "success" },
      { tone: "neutral", name: "결재선 템플릿", line3: "3단계 · 부서장 → 정보보안 → 대표" },
    ],
    footerText: "모바일에서는 승인 · 반려만 가능합니다",
    footerBtn: "승인",
  },
  {
    id: "reports",
    navLabel: "리포트",
    navDot: "#3B7A94",
    title: "리포트",
    sub: "주간 · 9월 1주",
    caption: "관리자 · 리포트",
    chips: ["주간", "월간"],
    rows: [
      { tone: "info", name: "수발신 추이", meta: "+6.2%", line3: "수신 168만 · 발송 81만" },
      { tone: "neutral", name: "스팸 차단률", meta: "99.2%", line3: "오탐 신고 12건", tag: "정상", tagTone: "success" },
      { tone: "neutral", name: "사용자 활성도", meta: "94%", line3: "주 5일 이상 접속 1,207명" },
      { tone: "neutral", name: "저장 용량 증가", meta: "+82 GB", line3: "주 평균 · 임계 예상 14개월" },
      { tone: "info", name: "예약 리포트", meta: "3건", line3: "월요일 08:00 · 경영진 발송", on: true },
    ],
    footerText: "PDF 내보내기는 데스크톱에서 가능합니다",
  },
  {
    id: "migration",
    navLabel: "마이그레이션",
    navDot: "#E0AC4A",
    title: "마이그레이션",
    sub: "배치 4개 진행 · 62%",
    caption: "관리자 · 마이그레이션",
    chips: ["진행", "완료", "실패"],
    rows: [
      { tone: "info", name: "배치 07 · 영업본부", meta: "82%", line3: "312/380 계정 · 남은 1시간 40분", on: true },
      { tone: "info", name: "배치 08 · 연구소", meta: "54%", line3: "104/192 계정 · 대역폭 제한" },
      { tone: "neutral", name: "배치 09 · 해외지사", meta: "21%", line3: "38/180 계정 · 시차 대기" },
      { tone: "danger", name: "배치 06 · 실패 4건", line3: "메일함 용량 초과 · 재시도 필요", tag: "실패", tagTone: "danger" },
      { tone: "success", name: "배치 01–05 완료", meta: "612", line3: "검증 통과 · 원본 보관 30일", tag: "완료", tagTone: "success" },
    ],
    footerText: "중단 · 재시도는 데스크톱 콘솔에서",
  },
];
